[features]
seeds = false
[programs.devnet]
marketplace_program = "ENvyfhonJeXYyq4y3dC4vVBsfejBKXJDBcW5nRUFqPsV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/username/.config/solana/id.json"

[scripts]
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
